// AUTO-GENERATED by carly-cli/scripts/gen-n8n-node.ts — DO NOT EDIT BY HAND.
// Regenerate with `npm run gen:n8n` from the carly-cli repo.
// Source of truth: carly-cli/src/commands/**.

import type { INodeType, INodeTypeDescription } from 'n8n-workflow';

export class Carly implements INodeType {
  description: INodeTypeDescription = {
  displayName: "Carly",
  name: "carly",
  icon: "file:carly.png",
  group: [
    "transform"
  ],
  version: 1,
  subtitle: "={{$parameter[\"operation\"] + \": \" + $parameter[\"resource\"]}}",
  description: "Read and manage Carly booking pages, event types, calendars, and bookings",
  defaults: {
    name: "Carly"
  },
  usableAsTool: true,
  inputs: [
    "main"
  ],
  outputs: [
    "main"
  ],
  credentials: [
    {
      name: "carlyApi",
      required: true
    }
  ],
  requestDefaults: {
    baseURL: "={{$credentials.baseUrl}}",
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json"
    }
  },
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      noDataExpression: true,
      options: [
        {
          name: "Booking",
          value: "bookings"
        },
        {
          name: "Booking Page",
          value: "booking-pages"
        },
        {
          name: "Calendar",
          value: "calendars"
        },
        {
          name: "Event Type",
          value: "event-types"
        },
        {
          name: "Profile",
          value: "profile"
        },
        {
          name: "Slot",
          value: "slots"
        }
      ],
      default: "profile"
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      noDataExpression: true,
      displayOptions: {
        show: {
          resource: [
            "profile"
          ]
        }
      },
      options: [
        {
          name: "Whoami",
          value: "whoami",
          action: "Get profile",
          description: "Show the user the API key belongs to",
          routing: {
            request: {
              method: "GET",
              url: "/whoami"
            }
          }
        }
      ],
      default: "whoami"
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      noDataExpression: true,
      displayOptions: {
        show: {
          resource: [
            "calendars"
          ]
        }
      },
      options: [
        {
          name: "List",
          value: "list",
          action: "List calendars",
          description: "List connected calendars for the authenticated user. The `selected` field mirrors the \"Check for conflicts on\" state in the web UI — calendars with `selected: true` count against booking-page availability.",
          routing: {
            request: {
              method: "GET",
              url: "/calendars"
            }
          }
        },
        {
          name: "Select",
          value: "select",
          action: "Add a calendar to availability",
          description: "Mark a calendar as counting against booking-page availability (\"Check for conflicts on\"). Requires the `booking_pages:write` scope. The flag is account-wide — every booking page on this calendar's integration will honor it on the next availability check.",
          routing: {
            request: {
              method: "POST",
              url: "/calendars/select",
              body: {
                selected: true
              }
            }
          }
        },
        {
          name: "Unselect",
          value: "unselect",
          action: "Remove a calendar from availability",
          description: "Stop counting a calendar against booking-page availability. Requires the `booking_pages:write` scope. Inverse of `carly calendars select`.",
          routing: {
            request: {
              method: "POST",
              url: "/calendars/select",
              body: {
                selected: false
              }
            }
          }
        }
      ],
      default: "list"
    },
    {
      displayName: "Calendar Key",
      name: "calendar_key",
      type: "string",
      required: true,
      default: "",
      displayOptions: {
        show: {
          resource: [
            "calendars"
          ],
          operation: [
            "select"
          ]
        }
      },
      routing: {
        send: {
          type: "body",
          property: "calendar_key"
        }
      }
    },
    {
      displayName: "Calendar Key",
      name: "calendar_key",
      type: "string",
      required: true,
      default: "",
      displayOptions: {
        show: {
          resource: [
            "calendars"
          ],
          operation: [
            "unselect"
          ]
        }
      },
      routing: {
        send: {
          type: "body",
          property: "calendar_key"
        }
      }
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      noDataExpression: true,
      displayOptions: {
        show: {
          resource: [
            "booking-pages"
          ]
        }
      },
      options: [
        {
          name: "Create",
          value: "create",
          action: "Create a booking page",
          description: "Create a new booking page. Requires the `booking_pages:write` scope. Accepts nested fields (--availability, --custom-questions, --duration-options, --widgets) as JSON. Availability calendars are not settable on create — a new page uses the account-wide conflict-check selection until you narrow it with an update.",
          routing: {
            request: {
              method: "POST",
              url: "/booking-pages"
            }
          }
        },
        {
          name: "Delete",
          value: "delete",
          action: "Delete a booking page",
          description: "Deactivate (pause) a booking page by its event type ID. The server soft-deletes: the page is hidden from public booking (is_active=false) but the row is retained and the page can be re-activated via `update &lt;ID&gt; --is-active true`. Requires the `booking_pages:write` scope.",
          routing: {
            request: {
              method: "DELETE",
              url: "=/booking-pages/{{$parameter[\"eventTypeId\"]}}"
            }
          }
        },
        {
          name: "Get",
          value: "get",
          action: "Get a booking page",
          description: "Get a single booking page by its event type ID",
          routing: {
            request: {
              method: "GET",
              url: "=/booking-pages/{{$parameter[\"eventTypeId\"]}}"
            }
          }
        },
        {
          name: "List",
          value: "list",
          action: "List booking pages",
          description: "List the authenticated user's booking pages (event types with public links)",
          routing: {
            request: {
              method: "GET",
              url: "/booking-pages"
            }
          }
        },
        {
          name: "Update",
          value: "update",
          action: "Update a booking page",
          description: "Update an existing booking page by its event type ID. Requires the `booking_pages:write` scope. Only fields you pass are updated. Nested fields (--availability, --custom-questions, --duration-options, --widgets, --availability-calendar-keys) accept JSON and replace the previous value.",
          routing: {
            request: {
              method: "PATCH",
              url: "=/booking-pages/{{$parameter[\"eventTypeId\"]}}"
            }
          }
        }
      ],
      default: "list"
    },
    {
      displayName: "Event Type ID",
      name: "eventTypeId",
      type: "number",
      required: true,
      default: 0,
      displayOptions: {
        show: {
          resource: [
            "booking-pages"
          ],
          operation: [
            "get"
          ]
        }
      }
    },
    {
      displayName: "Title",
      name: "title",
      type: "string",
      required: true,
      default: "",
      displayOptions: {
        show: {
          resource: [
            "booking-pages"
          ],
          operation: [
            "create"
          ]
        }
      },
      description: "Page title (required)",
      routing: {
        send: {
          type: "body",
          property: "title"
        }
      }
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      placeholder: "Add Field",
      default: {},
      displayOptions: {
        show: {
          resource: [
            "booking-pages"
          ],
          operation: [
            "create"
          ]
        }
      },
      options: [
        {
          displayName: "After Event Buffer",
          name: "afterEventBuffer",
          type: "number",
          default: 0,
          description: "Buffer after each meeting (minutes)",
          routing: {
            send: {
              type: "body",
              property: "afterEventBuffer"
            }
          }
        },
        {
          displayName: "Availability",
          name: "availability",
          type: "json",
          default: "",
          description: "Weekly availability as JSON: [{\"days\":[1,2,3,4,5],\"start_time\":\"09:00\",\"end_time\":\"17:00\"}] (days: Sun=0..Sat=6)",
          routing: {
            send: {
              type: "body",
              property: "availability"
            }
          }
        },
        {
          displayName: "Before Event Buffer",
          name: "beforeEventBuffer",
          type: "number",
          default: 0,
          description: "Buffer before each meeting (minutes)",
          routing: {
            send: {
              type: "body",
              property: "beforeEventBuffer"
            }
          }
        },
        {
          displayName: "Calendar Key",
          name: "calendarKey",
          type: "string",
          default: "",
          description: "Target calendar key (see `carly calendars list`)",
          routing: {
            send: {
              type: "body",
              property: "calendarKey"
            }
          }
        },
        {
          displayName: "Collect Company",
          name: "collectCompany",
          type: "boolean",
          default: false,
          description: "Whether to ask the guest for a company name",
          routing: {
            send: {
              type: "body",
              property: "collectCompany"
            }
          }
        },
        {
          displayName: "Collect Phone",
          name: "collectPhone",
          type: "boolean",
          default: false,
          description: "Whether to ask the guest for a phone number",
          routing: {
            send: {
              type: "body",
              property: "collectPhone"
            }
          }
        },
        {
          displayName: "Custom Questions",
          name: "customQuestions",
          type: "json",
          default: "",
          description: "Custom questions as JSON: [{\"label\":\"Company\",\"type\":\"text\",\"required\":true}]",
          routing: {
            send: {
              type: "body",
              property: "customQuestions"
            }
          }
        },
        {
          displayName: "Description",
          name: "description",
          type: "string",
          default: "",
          description: "Page description",
          routing: {
            send: {
              type: "body",
              property: "description"
            }
          }
        },
        {
          displayName: "Display Name",
          name: "displayName",
          type: "string",
          default: "",
          description: "Public display name on the booking page",
          routing: {
            send: {
              type: "body",
              property: "displayName"
            }
          }
        },
        {
          displayName: "Duration",
          name: "duration",
          type: "number",
          default: 0,
          description: "Meeting length in minutes",
          routing: {
            send: {
              type: "body",
              property: "duration"
            }
          }
        },
        {
          displayName: "Duration Options",
          name: "durationOptions",
          type: "json",
          default: "",
          description: "Bookable durations as CSV (15,30,60) or JSON array ([15,30,60])",
          routing: {
            send: {
              type: "body",
              property: "durationOptions"
            }
          }
        },
        {
          displayName: "Event Name Template",
          name: "eventNameTemplate",
          type: "string",
          default: "",
          description: "Template for generated event titles",
          routing: {
            send: {
              type: "body",
              property: "eventNameTemplate"
            }
          }
        },
        {
          displayName: "Location",
          name: "location",
          type: "string",
          default: "",
          description: "Meeting location (physical or URL)",
          routing: {
            send: {
              type: "body",
              property: "location"
            }
          }
        },
        {
          displayName: "Max Days Ahead",
          name: "maxDaysAhead",
          type: "number",
          default: 0,
          description: "Max days ahead a booking can be placed",
          routing: {
            send: {
              type: "body",
              property: "maxDaysAhead"
            }
          }
        },
        {
          displayName: "Min Notice Minutes",
          name: "minNoticeMinutes",
          type: "number",
          default: 0,
          description: "Minimum notice before a booking (minutes)",
          routing: {
            send: {
              type: "body",
              property: "minNoticeMinutes"
            }
          }
        },
        {
          displayName: "Notification Email",
          name: "notificationEmail",
          type: "string",
          default: "",
          description: "Send new-booking notifications here instead of the account email",
          routing: {
            send: {
              type: "body",
              property: "notificationEmail"
            }
          }
        },
        {
          displayName: "Slot Interval",
          name: "slotInterval",
          type: "number",
          default: 0,
          description: "Slot interval override (minutes)",
          routing: {
            send: {
              type: "body",
              property: "slotInterval"
            }
          }
        },
        {
          displayName: "Slug",
          name: "slug",
          type: "string",
          default: "",
          description: "URL slug (e.g. \"15min\")",
          routing: {
            send: {
              type: "body",
              property: "slug"
            }
          }
        },
        {
          displayName: "Timezone",
          name: "timezone",
          type: "string",
          default: "",
          description: "IANA timezone (e.g. America/New_York)",
          routing: {
            send: {
              type: "body",
              property: "timezone"
            }
          }
        },
        {
          displayName: "Username",
          name: "username",
          type: "string",
          default: "",
          description: "Profile username (lowercase, a-z0-9-)",
          routing: {
            send: {
              type: "body",
              property: "username"
            }
          }
        },
        {
          displayName: "Video Provider",
          name: "videoProvider",
          type: "string",
          default: "",
          description: "Video provider (google_meet, teams, zoom, ...)",
          routing: {
            send: {
              type: "body",
              property: "videoProvider"
            }
          }
        },
        {
          displayName: "Widgets",
          name: "widgets",
          type: "json",
          default: "",
          description: "Page content blocks as JSON, max 20. Each block has a type — video, image, text, link, or testimonial — plus that type's fields, e.g. {\"type\":\"text\",\"heading\":\"About\",\"body\":\"...\"}.",
          routing: {
            send: {
              type: "body",
              property: "widgets"
            }
          }
        }
      ]
    },
    {
      displayName: "Event Type ID",
      name: "eventTypeId",
      type: "number",
      required: true,
      default: 0,
      displayOptions: {
        show: {
          resource: [
            "booking-pages"
          ],
          operation: [
            "update"
          ]
        }
      }
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      placeholder: "Add Field",
      default: {},
      displayOptions: {
        show: {
          resource: [
            "booking-pages"
          ],
          operation: [
            "update"
          ]
        }
      },
      options: [
        {
          displayName: "After Event Buffer",
          name: "afterEventBuffer",
          type: "number",
          default: 0,
          description: "Buffer after each meeting (minutes)",
          routing: {
            send: {
              type: "body",
              property: "afterEventBuffer"
            }
          }
        },
        {
          displayName: "Availability",
          name: "availability",
          type: "json",
          default: "",
          description: "Weekly availability as JSON: [{\"days\":[1,2,3,4,5],\"start_time\":\"09:00\",\"end_time\":\"17:00\"}] (days: Sun=0..Sat=6)",
          routing: {
            send: {
              type: "body",
              property: "availability"
            }
          }
        },
        {
          displayName: "Availability Calendar Keys",
          name: "availabilityCalendarKeys",
          type: "json",
          default: "",
          description: "Calendars that block availability on THIS page, as JSON: [{\"provider\":\"google\",\"integration_id\":12,\"calendar_id\":\"primary\"}] (see `carly calendars list`)",
          routing: {
            send: {
              type: "body",
              property: "availabilityCalendarKeys"
            }
          }
        },
        {
          displayName: "Before Event Buffer",
          name: "beforeEventBuffer",
          type: "number",
          default: 0,
          description: "Buffer before each meeting (minutes)",
          routing: {
            send: {
              type: "body",
              property: "beforeEventBuffer"
            }
          }
        },
        {
          displayName: "Calendar Key",
          name: "calendarKey",
          type: "string",
          default: "",
          description: "Target calendar key (see `carly calendars list`)",
          routing: {
            send: {
              type: "body",
              property: "calendarKey"
            }
          }
        },
        {
          displayName: "Collect Company",
          name: "collectCompany",
          type: "boolean",
          default: false,
          description: "Whether to ask the guest for a company name",
          routing: {
            send: {
              type: "body",
              property: "collectCompany"
            }
          }
        },
        {
          displayName: "Collect Phone",
          name: "collectPhone",
          type: "boolean",
          default: false,
          description: "Whether to ask the guest for a phone number",
          routing: {
            send: {
              type: "body",
              property: "collectPhone"
            }
          }
        },
        {
          displayName: "Custom Questions",
          name: "customQuestions",
          type: "json",
          default: "",
          description: "Custom questions as JSON: [{\"label\":\"Company\",\"type\":\"text\",\"required\":true}]",
          routing: {
            send: {
              type: "body",
              property: "customQuestions"
            }
          }
        },
        {
          displayName: "Description",
          name: "description",
          type: "string",
          default: "",
          description: "Page description",
          routing: {
            send: {
              type: "body",
              property: "description"
            }
          }
        },
        {
          displayName: "Display Name",
          name: "displayName",
          type: "string",
          default: "",
          description: "Public display name on the booking page",
          routing: {
            send: {
              type: "body",
              property: "displayName"
            }
          }
        },
        {
          displayName: "Duration",
          name: "duration",
          type: "number",
          default: 0,
          description: "Meeting length in minutes",
          routing: {
            send: {
              type: "body",
              property: "duration"
            }
          }
        },
        {
          displayName: "Duration Options",
          name: "durationOptions",
          type: "json",
          default: "",
          description: "Bookable durations as CSV (15,30,60) or JSON array ([15,30,60])",
          routing: {
            send: {
              type: "body",
              property: "durationOptions"
            }
          }
        },
        {
          displayName: "Event Name Template",
          name: "eventNameTemplate",
          type: "string",
          default: "",
          description: "Template for generated event titles",
          routing: {
            send: {
              type: "body",
              property: "eventNameTemplate"
            }
          }
        },
        {
          displayName: "Is Active",
          name: "isActive",
          type: "boolean",
          default: false,
          description: "Whether to enable or disable the page",
          routing: {
            send: {
              type: "body",
              property: "isActive"
            }
          }
        },
        {
          displayName: "Location",
          name: "location",
          type: "string",
          default: "",
          description: "Meeting location (physical or URL)",
          routing: {
            send: {
              type: "body",
              property: "location"
            }
          }
        },
        {
          displayName: "Max Days Ahead",
          name: "maxDaysAhead",
          type: "number",
          default: 0,
          description: "Max days ahead a booking can be placed",
          routing: {
            send: {
              type: "body",
              property: "maxDaysAhead"
            }
          }
        },
        {
          displayName: "Min Notice Minutes",
          name: "minNoticeMinutes",
          type: "number",
          default: 0,
          description: "Minimum notice before a booking (minutes)",
          routing: {
            send: {
              type: "body",
              property: "minNoticeMinutes"
            }
          }
        },
        {
          displayName: "Notification Email",
          name: "notificationEmail",
          type: "string",
          default: "",
          description: "Send new-booking notifications here instead of the account email",
          routing: {
            send: {
              type: "body",
              property: "notificationEmail"
            }
          }
        },
        {
          displayName: "Slot Interval",
          name: "slotInterval",
          type: "number",
          default: 0,
          description: "Slot interval override (minutes)",
          routing: {
            send: {
              type: "body",
              property: "slotInterval"
            }
          }
        },
        {
          displayName: "Slug",
          name: "slug",
          type: "string",
          default: "",
          description: "URL slug (e.g. \"15min\")",
          routing: {
            send: {
              type: "body",
              property: "slug"
            }
          }
        },
        {
          displayName: "Timezone",
          name: "timezone",
          type: "string",
          default: "",
          description: "IANA timezone (e.g. America/New_York)",
          routing: {
            send: {
              type: "body",
              property: "timezone"
            }
          }
        },
        {
          displayName: "Title",
          name: "title",
          type: "string",
          default: "",
          description: "Page title",
          routing: {
            send: {
              type: "body",
              property: "title"
            }
          }
        },
        {
          displayName: "Username",
          name: "username",
          type: "string",
          default: "",
          description: "Profile username (lowercase, a-z0-9-)",
          routing: {
            send: {
              type: "body",
              property: "username"
            }
          }
        },
        {
          displayName: "Video Provider",
          name: "videoProvider",
          type: "string",
          default: "",
          description: "Video provider (google_meet, teams, zoom, ...)",
          routing: {
            send: {
              type: "body",
              property: "videoProvider"
            }
          }
        },
        {
          displayName: "Widgets",
          name: "widgets",
          type: "json",
          default: "",
          description: "Page content blocks as JSON, max 20. Each block has a type — video, image, text, link, or testimonial — plus that type's fields, e.g. {\"type\":\"text\",\"heading\":\"About\",\"body\":\"...\"}.",
          routing: {
            send: {
              type: "body",
              property: "widgets"
            }
          }
        }
      ]
    },
    {
      displayName: "Event Type ID",
      name: "eventTypeId",
      type: "number",
      required: true,
      default: 0,
      displayOptions: {
        show: {
          resource: [
            "booking-pages"
          ],
          operation: [
            "delete"
          ]
        }
      }
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      noDataExpression: true,
      displayOptions: {
        show: {
          resource: [
            "event-types"
          ]
        }
      },
      options: [
        {
          name: "List",
          value: "list",
          action: "List event types",
          description: "List event types. Without --username, returns the authenticated caller's own event types. With --username, returns that public profile's active event types.",
          routing: {
            request: {
              method: "GET",
              url: "/event-types"
            }
          }
        }
      ],
      default: "list"
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      placeholder: "Add Field",
      default: {},
      displayOptions: {
        show: {
          resource: [
            "event-types"
          ],
          operation: [
            "list"
          ]
        }
      },
      options: [
        {
          displayName: "Username",
          name: "username",
          type: "string",
          default: "",
          description: "Filter to this profile's active event types instead of the caller's",
          routing: {
            send: {
              type: "query",
              property: "username"
            }
          }
        }
      ]
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      noDataExpression: true,
      displayOptions: {
        show: {
          resource: [
            "slots"
          ]
        }
      },
      options: [
        {
          name: "List",
          value: "list",
          action: "List slots",
          description: "List available booking slots in a time range. Provide either --event-type-ID, or both --username and --event-type-slug.",
          routing: {
            request: {
              method: "GET",
              url: "/slots"
            }
          }
        }
      ],
      default: "list"
    },
    {
      displayName: "Start Time",
      name: "startTime",
      type: "string",
      required: true,
      default: "",
      displayOptions: {
        show: {
          resource: [
            "slots"
          ],
          operation: [
            "list"
          ]
        }
      },
      description: "Range start (ISO 8601)",
      routing: {
        send: {
          type: "query",
          property: "startTime"
        }
      }
    },
    {
      displayName: "End Time",
      name: "endTime",
      type: "string",
      required: true,
      default: "",
      displayOptions: {
        show: {
          resource: [
            "slots"
          ],
          operation: [
            "list"
          ]
        }
      },
      description: "Range end (ISO 8601)",
      routing: {
        send: {
          type: "query",
          property: "endTime"
        }
      }
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      placeholder: "Add Field",
      default: {},
      displayOptions: {
        show: {
          resource: [
            "slots"
          ],
          operation: [
            "list"
          ]
        }
      },
      options: [
        {
          displayName: "Duration",
          name: "duration",
          type: "number",
          default: 0,
          description: "Override slot duration (minutes)",
          routing: {
            send: {
              type: "query",
              property: "duration"
            }
          }
        },
        {
          displayName: "Event Type ID",
          name: "eventTypeId",
          type: "number",
          default: 0,
          routing: {
            send: {
              type: "query",
              property: "eventTypeId"
            }
          }
        },
        {
          displayName: "Event Type Slug",
          name: "eventTypeSlug",
          type: "string",
          default: "",
          description: "Event type slug (with --username)",
          routing: {
            send: {
              type: "query",
              property: "eventTypeSlug"
            }
          }
        },
        {
          displayName: "Username",
          name: "username",
          type: "string",
          default: "",
          description: "Profile username (with --event-type-slug)",
          routing: {
            send: {
              type: "query",
              property: "username"
            }
          }
        }
      ]
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      noDataExpression: true,
      displayOptions: {
        show: {
          resource: [
            "bookings"
          ]
        }
      },
      options: [
        {
          name: "Get",
          value: "get",
          action: "Get a booking",
          description: "Get a single booking by its UID",
          routing: {
            request: {
              method: "GET",
              url: "=/bookings/{{$parameter[\"uid\"]}}"
            }
          }
        },
        {
          name: "List",
          value: "list",
          action: "List bookings",
          description: "List the authenticated user's bookings. Supports filters for status, event type, and time range.",
          routing: {
            request: {
              method: "GET",
              url: "/bookings"
            }
          }
        }
      ],
      default: "list"
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      placeholder: "Add Field",
      default: {},
      displayOptions: {
        show: {
          resource: [
            "bookings"
          ],
          operation: [
            "list"
          ]
        }
      },
      options: [
        {
          displayName: "End Time",
          name: "endTime",
          type: "string",
          default: "",
          description: "Range end (ISO 8601)",
          routing: {
            send: {
              type: "query",
              property: "endTime"
            }
          }
        },
        {
          displayName: "Event Type ID",
          name: "eventTypeId",
          type: "number",
          default: 0,
          description: "Filter by event type ID",
          routing: {
            send: {
              type: "query",
              property: "eventTypeId"
            }
          }
        },
        {
          displayName: "Limit",
          name: "limit",
          type: "number",
          default: 50,
          typeOptions: {
            minValue: 1
          },
          description: "Max number of results to return",
          routing: {
            send: {
              type: "query",
              property: "limit"
            }
          }
        },
        {
          displayName: "Start Time",
          name: "startTime",
          type: "string",
          default: "",
          description: "Range start (ISO 8601)",
          routing: {
            send: {
              type: "query",
              property: "startTime"
            }
          }
        },
        {
          displayName: "Status",
          name: "status",
          type: "string",
          default: "",
          description: "Filter by booking status",
          routing: {
            send: {
              type: "query",
              property: "status"
            }
          }
        }
      ]
    },
    {
      displayName: "UID",
      name: "uid",
      type: "string",
      required: true,
      default: "",
      displayOptions: {
        show: {
          resource: [
            "bookings"
          ],
          operation: [
            "get"
          ]
        }
      }
    }
  ]
};
}
